### ISSUE TITLE
upload video

### ISSUE THREAD

**Issue by VReunov** [Dropout1337/Triller-API-Docs#6]
I need help, at the /video/upload stage I get error 1014 (Need both png thumbnail and video file). I work through requests (python)

**Comment by Dropout1337** [comment]
You will have to use something like fiddler4 to fully understand how triller's upload endpoint works. I no longer update/work on stuff involving triller.

**Comment by VReunov** [comment]
Response from support ¯\_(ツ)_/¯
![Снимок экрана 2021-04-25 в 13 48 09](https://user-images.githubusercontent.com/2165575/115990634-ecd18e80-a5cc-11eb-81a0-de3ed1c41c63.png)
